// src/mocks/learningMockData.ts
import type { Category } from "@/types/lms";

export const mockCategories: Category[] = [
  {
    id: "1",
    title: "Web Development",
    description: "Learn to build modern, responsive websites and applications.",
    image: "./images/programming-icon.svg",
    inProgress: true,
    courses: [
      {
        id: 2,
        title: "Introduction to HTML & CSS",
        slug: "intro-to-html-css",
        thumbnail: "./images/courses/cs.svg",
        is_new: true,
        description: "",
        progress: 10,
        level: "beginner",
        category_id: "web-dev",
        modules: [],
        author_id: "demo-author",
        is_published: true,
        module_count: 0,
        created_at: "2024-01-01T00:00:00Z",
        updated_at: "2024-01-01T00:00:00Z",
      },
      {
        id: 3,
        title: "JavaScript Essentials",
        slug: "javascript-essentials",
        thumbnail: "./images/courses/ai.svg",
        is_new: false,
        description: "",
        level: "beginner",
        progress: 0,
        category_id: "web-dev",
        modules: [],
        author_id: "demo-author",
        is_published: true,
        module_count: 0,
        created_at: "2024-01-01T00:00:00Z",
        updated_at: "2024-01-01T00:00:00Z",
      },
    ],
  },
  {
    id: "4",
    title: "Data Science",
    description: "Master data analysis, visualization, and machine learning.",
    image: "./images/math-icon.svg",

    courses: [
      {
        id: 7,
        title: "Python for Data Analysis",
        slug: "python-data-analysis",
        thumbnail: "./images/courses/python.svg",
        is_new: false,
        description: "",
        level: "beginner",
        progress: 0,
        category_id: "data-science",
        modules: [],
        author_id: "demo-author",
        is_published: true,
        module_count: 0,
        created_at: "2024-01-01T00:00:00Z",
        updated_at: "2024-01-01T00:00:00Z",
      },
      {
        id: 6,
        title: "Introduction to Machine Learning",
        slug: "intro-to-ml",
        thumbnail: "./images/courses/ai.svg",
        is_new: true,
        description: "",
        level: "beginner",
        progress: 0,
        category_id: "ai",
        modules: [],
        author_id: "demo-author",
        is_published: false,
        module_count: 0,
        created_at: "2024-01-01T00:00:00Z",
        updated_at: "2024-01-01T00:00:00Z",
      },
    ],
    inProgress: false,
  },
];
